Add scuffed battle.
Crepe-Inc/CrepeSR pull request #64
Opened 2022-08-07 18:37 UTC by GanyusLeftHorn

2022-08-07 19:17 UTC, memetrollsXD reviewed
From just testing the command itself, it works on specific conditions only:

Tested using `battle 102202001 102202001`
- Plane ID needs to be correct type - Testing the above command on Forgotten Hall will brick the client, but if tested in Southern Snow Plains it will work perfectly.

2022-08-08 03:37 UTC, TheLostTree requested changes
Generally I'd prefer if y'all didn't use the as keyword 😔 type.fromPartial() should be your goto unless it won't work otherwise

2022-08-08 03:37 UTC, TheLostTree commented on src/commands/battle.ts
> +                } as unknown as BattleAvatar;
try to use BattleAvatar.fromPartial instead of the as keyword when possible

2022-08-08 03:37 UTC, TheLostTree commented on src/commands/battle.ts
> +            heroPathList: [] as HeroPath[],
y'all can do ``new Array<HeroPath>() ``as well

2022-08-10 03:11 UTC, TheLostTree approved these changes
so hot

2022-08-10 03:11 UTC, merged